import { Job, JobDetails } from "@/features/job-search/types/job.types"

export const mockJobs: Job[] = [
  {
    id: 1,
    title: "Senior Frontend Developer",
    company: "TechCorp Inc.",
    location: "San Francisco, CA",
    remote: true,
    hybrid: false,
    salary: { min: 120000, max: 180000, currency: "USD" },
    type: "Full-time",
    posted: "2 days ago",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    companySize: "500-1000",
    skillMatch: 95,
    description:
      "We're looking for a senior frontend developer to join our growing team and help build the next generation of our web applications.",
    benefits: ["Health Insurance", "401k", "Remote Work", "Flexible Hours"],
    companyRating: 4.5,
    companyReviews: 234,
    experienceLevel: "Senior",
    department: "Engineering",
    isUrgent: false,
    isSponsored: true,
  },
  {
    id: 2,
    title: "Full Stack Engineer",
    company: "StartupXYZ",
    location: "New York, NY",
    remote: false,
    hybrid: true,
    salary: { min: 100000, max: 140000, currency: "USD" },
    type: "Full-time",
    posted: "1 day ago",
    skills: ["Node.js", "React", "PostgreSQL", "AWS"],
    companySize: "50-100",
    skillMatch: 87,
    description: "Join our fast-growing startup as a full stack engineer and help shape the future of our platform.",
    benefits: ["Equity", "Health Insurance", "Lunch Provided"],
    companyRating: 4.2,
    companyReviews: 89,
    experienceLevel: "Mid",
    department: "Engineering",
    isUrgent: true,
    isSponsored: false,
  },
  {
    id: 3,
    title: "React Developer",
    company: "Digital Agency Pro",
    location: "Austin, TX",
    remote: true,
    hybrid: false,
    salary: { min: 80000, max: 120000, currency: "USD" },
    type: "Contract",
    posted: "3 days ago",
    skills: ["React", "JavaScript", "CSS", "Git"],
    companySize: "10-50",
    skillMatch: 78,
    description: "We need a skilled React developer for client projects with modern web technologies.",
    benefits: ["Flexible Hours", "Remote Work"],
    companyRating: 4.0,
    companyReviews: 45,
    experienceLevel: "Mid",
    department: "Engineering",
    isUrgent: false,
    isSponsored: false,
  },
  {
    id: 4,
    title: "Senior Software Engineer",
    company: "Enterprise Solutions",
    location: "Seattle, WA",
    remote: true,
    hybrid: true,
    salary: { min: 140000, max: 200000, currency: "USD" },
    type: "Full-time",
    posted: "1 week ago",
    skills: ["Python", "Django", "React", "Docker"],
    companySize: "1000+",
    skillMatch: 82,
    description: "Lead development of enterprise-grade applications with cutting-edge technologies.",
    benefits: ["Health Insurance", "401k", "Stock Options", "Remote Work"],
    companyRating: 4.3,
    companyReviews: 567,
    experienceLevel: "Senior",
    department: "Engineering",
    isUrgent: false,
    isSponsored: true,
  },
]

export const getJobDetails = (id: number): JobDetails | null => {
  const job = mockJobs.find((j) => j.id === id)
  if (!job) return null

  return {
    ...job,
    requirements: [
      "5+ years of experience with React and modern JavaScript",
      "Strong proficiency in TypeScript",
      "Experience with Next.js and server-side rendering",
      "Solid understanding of CSS and responsive design",
      "Experience with testing frameworks (Jest, React Testing Library)",
      "Familiarity with Git and collaborative development workflows",
      "Strong problem-solving skills and attention to detail",
      "Excellent communication and teamwork abilities",
    ],
    niceToHave: [
      "Experience with GraphQL",
      "Knowledge of backend technologies (Node.js, Python)",
      "Experience with cloud platforms (AWS, GCP, Azure)",
      "Familiarity with CI/CD pipelines",
      "Open source contributions",
    ],
    companyInfo: {
      about:
        "TechCorp Inc. is a leading technology company that builds innovative software solutions for businesses worldwide. Founded in 2010, we've grown to over 800 employees across multiple offices.",
      culture:
        "We believe in work-life balance, continuous learning, and creating an inclusive environment where everyone can thrive. Our team is collaborative, innovative, and passionate about technology.",
      perks: [
        "Competitive salary and equity package",
        "Comprehensive health, dental, and vision insurance",
        "401(k) with company matching",
        "Unlimited PTO policy",
        "Remote work flexibility",
        "Professional development budget",
        "Modern office with free snacks and drinks",
        "Team building events and company retreats",
      ],
      website: "https://techcorp.com",
      industry: "Technology",
      founded: 2010,
      headquarters: "San Francisco, CA",
    },
    applicationProcess: [
      "Submit your application with resume and cover letter",
      "Initial phone screening (30 minutes)",
      "Technical interview with coding challenge (1 hour)",
      "Team interview and culture fit (45 minutes)",
      "Final interview with hiring manager (30 minutes)",
      "Reference checks and offer",
    ],
    similarJobs: mockJobs.filter((j) => j.id !== id).slice(0, 3),
  }
}
